name: Docker Image CI for CSEG Tools

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mpi-serial: ["2.3.0"]
        # 1.10 needs to be a string or the trailing 0 is lost
        hdf5: ["1.10", "1.12"]
        netcdfc: [4.7.4, 4.8.1]
        netcdff: [4.5.4]
        include:
          - hdf5: "1.10"
            hdf5m: 8
          - hdf5: "1.12"
            hdf5m: 1
    steps:
    - name: Installs
      run: |
        python3 --version
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build the mpich Docker image
      uses: docker/build-push-action@v2
      with:
        push: true	
        tags:  ${{ secrets.DOCKER_HUB_USERNAME }}/ms${{ matrix.mpi-serial }}h${{ matrix.hdf5 }}nc${{ matrix.netcdfc }}nf${{ matrix.netcdff }}
        file: Dockerfile.mpi-serial
        build-args: |
          HDF5_VERSION_MAJOR=${{ matrix.hdf5 }}
          HDF5_VERSION_MINOR=${{ matrix.hdf5m }}
          NETCDF_C_VERSION=${{ matrix.netcdfc }}
          NETCDF_F_VERSION=${{ matrix.netcdff }}
          MPI_VERSION=${{ matrix.mpi-serial }}
