name: Docker Image CI for CSEG Tools

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
	username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: |
           docker --version
           docker build --file Dockerfile \
           --tag ${{ secrets.DOCKER_HUB_USERNAME }}/mpichbase:m3.4.3h1.10.8nc4.7.4nf4.5.4p1.12.3 \
           --build-arg HDF5_VERSION_MAJOR=1.10 \
           --build-arg HDF5_VERSION_MINOR=8 \
           --build-arg NETCDF_C_VERSION=4.7.4 \
	   --build-arg NETCDF_F_VERSION=4.5.4 \
	   --build-arg PNETCDF_VERSION=1.12.3 \
	   --build-arg MPI_VERSION=3.4.3 \
           .
    - name: Publish
      uses: docker/build-push-action@v2
      with:
        context: ./
	push: true
	tags:  ${{ secrets.DOCKER_HUB_USERNAME }}/mpichbase:m3.4.3h1.10.8nc4.7.4nf4.5.4p1.12.3
	cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/mpichbase:m3.4.3h1.10.8nc4.7.4nf4.5.4p1.12.3:buildcache
	cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/mpichbase:m3.4.3h1.10.8nc4.7.4nf4.5.4p1.12.3:buildcache,mode=max