name: Docker Image CI for CSEG Tools

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: Install
#      run: |
#           sudo apt-get update 
#           sudo apt-get install docker
    - name: Build the Docker image
      run: |
           docker --version
           docker build --file Dockerfile \
           --tag my-image-name:$(date +%s) \
           --build-arg HDF5_VERSION_MAJOR=1.10 \
           --build-arg HDF5_VERSION_MINOR=8 \
           .
